projectnexus/config/routes.rb
Projectnexus::Application.routes.draw do
  get "static_pages/about"

  get "static_pages/legal"

  resources :categories

  resources :messages

  resources :locations

  resources :supporters

  resources :authentications

  resources :projectresources

  resources :projecttags

  resources :levels

  resources :documents

  resources :resources

  resources :memberships

  resources :stages

  resources :comments

  resources :tags

  resources :discussions

  resources :blogentries

  resources :tasks

  resources :objectives

  resources :projects

  resources :collections

  match '/auth/facebook/callback' => 'authentications#create'

  resources :users
  
  root :to => 'index#index'
  
  match "/browse" => redirect("/projects")
  match "/projects/:id/home" => "projects#home"
  match "/signout" => "authentications#destroy", :as => :signout
  match "/projects/:id/people" => "memberships#index"
  match "/projects/:id/blog" => "blogentries#index"
  match "/projects/:id/blog/new" => "blogentries#new"
  match "/projects/:id/blog/:entry_id" => "blogentries#show"
  match "/projects/:id/blog/:entry_id/edit" => "blogentries#edit"

end

projectnexus/app/models/objective.rb
class Objective < ActiveRecord::Base
  validates_presence_of :description
  validates_presence_of :name

  belongs_to :project, :class_name => Project
  has_many :tasks, :foreign_key => "objective_id"
  has_many :documents, :foreign_key => "objective_id"
  attr_accessible :description, :name, :project_id
end

projectnexus/app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
layout false
  # GET /objectives
  # GET /objectives.json
  def index
    @objectives = Objective.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @objectives }
    end
  end

  # GET /objectives/1
  # GET /objectives/1.json
  def show
    @objective = Objective.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @objective }
    end
  end

  # GET /objectives/new
  # GET /objectives/new.json
  def new
    @project = Project.find(params[:project_id])
    @objective = Objective.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @objective }
    end
  end

  # GET /objectives/1/edit
  def edit
    @project = Project.find(params[:project_id])
    @objective = Objective.find(params[:id])
  end

  # POST /objectives
  # POST /objectives.json
  def create
    @objective = Objective.new(params[:objective])

    respond_to do |format|
      if @objective.save
        flash[:target] = 'objectives'
        format.html { redirect_to @objective.project, notice: 'Objective was successfully created.' }
        format.json { render json: @objective, status: :created, location: @objective }
      else
        format.html { render action: "new" }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /objectives/1
  # PUT /objectives/1.json
  def update
    @objective = Objective.find(params[:id])

    respond_to do |format|
      if @objective.update_attributes(params[:objective])
        format.html { redirect_to @objective, notice: 'Objective was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objectives/1
  # DELETE /objectives/1.json
  def destroy
    @objective = Objective.find(params[:id])
    @objective.destroy

    respond_to do |format|
      format.html { redirect_to objectives_url }
      format.json { head :no_content }
    end
  end
end

projectnexus/app/helpers/objectives_helper.rb
module ObjectivesHelper
end

projectnexus/app/views/objectives/_form.html.erb
<%= form_for([@project,@objective]) do |f| %>
  <% if @objective.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@objective.errors.count, "error") %> prohibited this objective from being saved:</h2>

      <ul>
      <% @objective.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

projectnexus/app/views/objectives/edit.html.erb
<h1>Editing objective</h1>

<%= render 'form' %>

<%= link_to 'Show', project_objective_path(:id => @objective.id, :project_id => params[:project_id]) %> |
<%= link_to 'Back', project_objectives_path %>

projectnexus/app/views/objectives/index.html.erb
<h1>Listing objectives</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @objectives.each do |objective| %>
  <tr>
    <td><%= objective.name %></td>
    <td><%= objective.description %></td>
    <td><%= objective.project_id %></td>
    <td><%= link_to 'Show', objective %></td>
    <td><%= link_to 'Edit', edit_objective_path(objective) %></td>
    <td><%= button_to 'Destroy', objective, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Objective', new_objective_path %>

projectnexus/app/views/objectives/new.html.erb
<h1>New objective</h1>

<%= render 'form' %>

<%= link_to 'Back', project_objectives_path %>

projectnexus/app/views/objectives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @objective.name %>
</p>

<p>
  <b>Description:</b>
  <%= @objective.description %>
</p>


<%= link_to 'Edit', edit_objective_path(@objective) %> |
<%= link_to 'Back', objectives_path %>