projectnexus/config/routes.rb
Projectnexus::Application.routes.draw do
  get "static_pages/about"

  get "static_pages/legal"

  resources :categories

  resources :messages

  resources :locations

  resources :supporters

  resources :authentications

  resources :projectresources

  resources :projecttags

  resources :levels

  resources :documents

  resources :resources

  resources :memberships

  resources :stages

  resources :comments

  resources :tags

  resources :discussions

  resources :blogentries

  resources :tasks

  resources :objectives

  resources :projects

  resources :collections

  match '/auth/facebook/callback' => 'authentications#create'

  resources :users
  
  root :to => 'index#index'
  
  match "/browse" => redirect("/projects")
  match "/projects/:id/home" => "projects#home"
  match "/signout" => "authentications#destroy", :as => :signout
  match "/projects/:id/people" => "memberships#index"
  match "/projects/:id/blog" => "blogentries#index"
  match "/projects/:id/blog/new" => "blogentries#new"
  match "/projects/:id/blog/:entry_id" => "blogentries#show"
  match "/projects/:id/blog/:entry_id/edit" => "blogentries#edit"

end

projectnexus/app/models/discussion.rb
class Discussion < ActiveRecord::Base
  
  validates_presence_of :name

  belongs_to :project
  has_many :comments

  attr_accessible :name
end

projectnexus/app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @discussions }
    end
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
    @discussion = Discussion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @discussion }
    end
  end

  # GET /discussions/new
  # GET /discussions/new.json
  def new
    @discussion = Discussion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @discussion }
    end
  end

  # GET /discussions/1/edit
  def edit
    @discussion = Discussion.find(params[:id])
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = Discussion.new(params[:discussion])

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: 'Discussion was successfully created.' }
        format.json { render json: @discussion, status: :created, location: @discussion }
      else
        format.html { render action: "new" }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /discussions/1
  # PUT /discussions/1.json
  def update
    @discussion = Discussion.find(params[:id])

    respond_to do |format|
      if @discussion.update_attributes(params[:discussion])
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion = Discussion.find(params[:id])
    @discussion.destroy

    respond_to do |format|
      format.html { redirect_to discussions_url }
      format.json { head :no_content }
    end
  end
end

projectnexus/app/helpers/discussions_helper.rb
module DiscussionsHelper
end

projectnexus/app/views/discussions/_form.html.erb
<%= form_for(@discussion) do |f| %>
  <% if @discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
      <% @discussion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

projectnexus/app/views/discussions/edit.html.erb
<h1>Editing discussion</h1>

<%= render 'form' %>

<%= link_to 'Show', @discussion %> |
<%= link_to 'Back', discussions_path %>

projectnexus/app/views/discussions/index.html.erb
<h1>Listing discussions</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @discussions.each do |discussion| %>
  <tr>
    <td><%= discussion.name %></td>
    <td><%= link_to 'Show', discussion %></td>
    <td><%= link_to 'Edit', edit_discussion_path(discussion) %></td>
    <td><%= link_to 'Destroy', discussion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Discussion', new_discussion_path %>

projectnexus/app/views/discussions/new.html.erb
<h1>New discussion</h1>

<%= render 'form' %>

<%= link_to 'Back', discussions_path %>

projectnexus/app/views/discussions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @discussion.name %>
</p>


<%= link_to 'Edit', edit_discussion_path(@discussion) %> |
<%= link_to 'Back', discussions_path %>